### ISSUE TITLE
This is not really an issue, it's a question for help

### ISSUE THREAD

**Issue by tb2johm** [vforteli/Flexinets.Ldap.Server#1]
I found this package when trying to simulate a very positive LDAP server.

A program I have found runs the following code. And if the `FindOne` operation doesn't throw an exception, the result is positive.

    var dsDirectoryEntry = new DirectoryEntry("LDAP://localhost", "user", "password");
    var ds = new DirectorySearcher(dsDirectoryEntry);
    try
    {
        var sr = ds.FindOne();
    }

Now all I want to do is to create a super basic server that just gives the correct answers to this request so that it will not throw. Any help or pointers would be highly appreciated!

**Comment by vforteli** [comment]
Well, I guess it may work as is by removing 
```
var searchRequest = requestPacket.ChildAttributes.SingleOrDefault(o => o.LdapOperation == LdapOperation.SearchRequest);
var filter = searchRequest.ChildAttributes[6];

if ((LdapFilterChoice)filter.ContextType == LdapFilterChoice.equalityMatch && filter.ChildAttributes[0].GetValue<String>() == "sAMAccountName" && filter.ChildAttributes[1].GetValue<String>() == "testuser") // equalityMatch
{
```
in LdapServer.cs. Then it will just return a user for any search request.
The bind credentials should probably also be changed here
```
if (username == "cn=user" && password == "password")
{
                response = LdapResult.success;
}
```

To run the server you would need to create a console/service/gui application and run 
```
var ldapserver = new LdapServer(new IPEndPoint(IPAddress.Any, 389));
ldapserver.Start();

**Comment by tb2johm** [comment]
Unfortunately that doesn't really work. This is the traffic I get when I run against a "real" LDAP server

![image](https://user-images.githubusercontent.com/3605706/39624247-db3b388e-4f98-11e8-8c52-b46dd6c3a722.png)

And the first difference I see is the "combined" searchResEntry and searchResDone

**Comment by vforteli** [comment]
The  searchResEntry and searchResDone looks a bit strange, but I guess thats just how the packet parser presents them.  They are separate ldap messages, but perhaps sent in the same segment. 
The real problem would be the NTLM authentication. It can probably be added, but thats not something I have looked into.

**Comment by tb2johm** [comment]
Ok, I think I found another workaround to the problem I had. Thanks a lot for your input.
