### ISSUE TITLE
Is there any way to support Schema in this implementation?

### ISSUE THREAD

**Issue by mgh9** [vforteli/Flexinets.Ldap.Server#9]
I want to support fetching schema operation in this implementation, so if anyone knows about it, I appreciate

**Comment by vforteli** [comment]
The intention of this project has never been to support all the database features of ldap, so while it technically would be possible to add something like this, in most cases the backend will not actually be an ldap database and wont have any concepts of a schema. Of course an endpoint could be made to return the schema, but that would anyway have to be tailor made for all handlers
